language: node_js
node_js:
- "12"
script:
- npm run build:client
- npm run build:server
after_success:
- scp -o StrictHostKeyChecking=no -r ./dist/* $REMOTE_HOST:~/web/infoweb/dist
- ssh -o StrictHostKeyChecking=no $REMOTE_HOST 'cd ~/web/infoweb && git pull && pm2 restart ecosystem.config.js
  --env production'
before_install:
- openssl aes-256-cbc -K $encrypted_e817fc780519_key -iv $encrypted_e817fc780519_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
